spring.security.user.name=admin
spring.security.user.password=admin123

spring.application.name=bigkart_customer

spring.datasource.url=jdbc:mysql://bigkart-db-server.c9cuu68as97f.ap-south-1.rds.amazonaws.com:3306/bigkart_customer_db?useSSL=true&trustServerCertificate=true

spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

# Kafka Configuration
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=bigkart-customer-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# JSP Configuration
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp